title: Maintenance Enforcement Division, a division of the Insolvency & Public
  Trustee's Office
url: https://med.mlaw.gov.sg
favicon: /images/MinLaw_logo.png
colors:
  primary-color: "#a40935"
  secondary-color: "#a40935"
  media-colors:
    - title: media-color-one
      color: "#696969"
    - title: media-color-two
      color: "#800000"
    - title: media-color-three
      color: "#00838f"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
description: Office of the Maintenance Enforcement Officers
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging-lite.d10w2vgd9qydoc.amplifyapp.com
prod: https://master.d2rudvgarph4ka.amplifyapp.com
facebook-pixel: ""
shareicon: /images/isomer-logo.svg
is_government: true
google_analytics_ga4: ""
linkedin-insights: ""
resources_name: maintenance-enforcement-resource-room
